import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
// import data from '../data/data.json';

const inter = Inter({ subsets: ["latin"] });


export async function getServerSideProps() {

  const {events_categories} = await import('../data/data.json') 

  return {
    props: {
      title: 'hello evcveryone',
      data: JSON.parse(JSON.stringify(events_categories))
    },
  }
}

interface HomeProps { 
  title: string;
  data: any;
}

const Home = ({title, data}: HomeProps)  => {
  console.log('insied of home', data);

  return (
    <>
      <Head>
        <title>Events App Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
        <header>
          <nav className={styles.nav}>
            <a href="/"> home </a>
            <a href="/about-us"> about us </a>
            <a href="/events"> events </a>
          </nav>
        </header>

        <main className={`${styles.main} ${inter.className}`}>
          {data && data.map((event: any, index: number) =>  {
            return (
              <a key={event.id} href={`/events/${event.id}`}>
                <Image 
                  src={event.image} 
                  alt={event.tittle}
                  width={200}
                  height={200}
                />
                <h2>{event.tittle}</h2>
                <p>{event.description}</p>
              </a>
            )})
            }
        </main>

        <footer className={styles.footer}>
          here is footer
        </footer>
    </>
  );
}

export default Home;
