import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });
interface HomeProps { 
  title: string;
}

const Home = ({title}: HomeProps)  => {
  return (
    <>
      <Head>
        <title>Events App Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
        <header>
          <nav className={styles.nav}>
            <a href="/"> home </a>
            <a href="/about-us"> about us </a>
            <a href="/events"> events </a>
          </nav>
        </header>

        <main className={`${styles.main} ${inter.className}`}>
          <a href="">
            <h1 className={styles.title}>
              Showing title Barcelona {title}
            </h1>
            <p>
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Itaque, aspernatur! Distinctio tenetur esse vel illo nihil dolor quis obcaecati, architecto quasi numquam ullam? Temporibus, eveniet quae ex nostrum nam voluptate.
            </p>
          </a>

          <a href="">
            <h1 className={styles.title}>
              event san francisco
            </h1>
            <p>
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Itaque, aspernatur! Distinctio tenetur esse vel illo nihil dolor quis obcaecati, architecto quasi numquam ullam? Temporibus, eveniet quae ex nostrum nam voluptate.
            </p>
          </a>

          <a href="">
            <h1 className={styles.title}>
             event london
            </h1>
            <p>
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Itaque, aspernatur! Distinctio tenetur esse vel illo nihil dolor quis obcaecati, architecto quasi numquam ullam? Temporibus, eveniet quae ex nostrum nam voluptate.
            </p>
          </a>
        </main>

        <footer className={styles.footer}>
          here is footer
        </footer>
    </>
  );
}

export default Home;

export function getServerSideProps() {
  return {
    props: {
      title: 'hello evcveryone' 
    },
  }
}